// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobuf/PDTLogger.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - PaperbackLogger

/// Namespace containing generated types for the "PaperbackLogger" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum PaperbackLogger {
    /// Service descriptor for the "PaperbackLogger" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackLogger")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "streamLogs" metadata.
        public enum streamLogs {
            /// Request type for "streamLogs".
            public typealias Input = LogFilter
            /// Response type for "streamLogs".
            public typealias Output = LogLine
            /// Descriptor for "streamLogs".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackLogger"),
                method: "streamLogs"
            )
        }
        /// Descriptors for all methods in the "PaperbackLogger" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            streamLogs.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "PaperbackLogger" service.
    public static let PaperbackLogger = GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackLogger")
}

// MARK: PaperbackLogger (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger {
    /// Streaming variant of the service protocol for the "PaperbackLogger" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "streamLogs" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `LogFilter` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `LogLine` messages.
        func streamLogs(
            request: GRPCCore.StreamingServerRequest<LogFilter>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<LogLine>
    }

    /// Service protocol for the "PaperbackLogger" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: PaperbackLogger.StreamingServiceProtocol {
        /// Handle the "streamLogs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LogFilter` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `LogLine` messages.
        func streamLogs(
            request: GRPCCore.ServerRequest<LogFilter>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<LogLine>
    }

    /// Simple service protocol for the "PaperbackLogger" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: PaperbackLogger.ServiceProtocol {
        /// Handle the "streamLogs" method.
        ///
        /// - Parameters:
        ///   - request: A `LogFilter` message.
        ///   - response: A response stream of `LogLine` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func streamLogs(
            request: LogFilter,
            response: GRPCCore.RPCWriter<LogLine>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: PaperbackLogger.Method.streamLogs.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<LogFilter>(),
            serializer: GRPCProtobuf.ProtobufSerializer<LogLine>(),
            handler: { request, context in
                try await self.streamLogs(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger.ServiceProtocol {
    public func streamLogs(
        request: GRPCCore.StreamingServerRequest<LogFilter>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<LogLine> {
        let response = try await self.streamLogs(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger.SimpleServiceProtocol {
    public func streamLogs(
        request: GRPCCore.ServerRequest<LogFilter>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<LogLine> {
        return GRPCCore.StreamingServerResponse<LogLine>(
            metadata: [:],
            producer: { writer in
                try await self.streamLogs(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: PaperbackLogger (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger {
    /// Generated client protocol for the "PaperbackLogger" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "streamLogs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LogFilter` message.
        ///   - serializer: A serializer for `LogFilter` messages.
        ///   - deserializer: A deserializer for `LogLine` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func streamLogs<Result>(
            request: GRPCCore.ClientRequest<LogFilter>,
            serializer: some GRPCCore.MessageSerializer<LogFilter>,
            deserializer: some GRPCCore.MessageDeserializer<LogLine>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<LogLine>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "PaperbackLogger" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "streamLogs" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LogFilter` message.
        ///   - serializer: A serializer for `LogFilter` messages.
        ///   - deserializer: A deserializer for `LogLine` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func streamLogs<Result>(
            request: GRPCCore.ClientRequest<LogFilter>,
            serializer: some GRPCCore.MessageSerializer<LogFilter>,
            deserializer: some GRPCCore.MessageDeserializer<LogLine>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<LogLine>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: PaperbackLogger.Method.streamLogs.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger.ClientProtocol {
    /// Call the "streamLogs" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `LogFilter` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamLogs<Result>(
        request: GRPCCore.ClientRequest<LogFilter>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<LogLine>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.streamLogs(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<LogFilter>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<LogLine>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackLogger.ClientProtocol {
    /// Call the "streamLogs" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func streamLogs<Result>(
        _ message: LogFilter,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<LogLine>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<LogFilter>(
            message: message,
            metadata: metadata
        )
        return try await self.streamLogs(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}