// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: protobuf/PDTSourceTester.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - PaperbackSourceTester

/// Namespace containing generated types for the "PaperbackSourceTester" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum PaperbackSourceTester {
    /// Service descriptor for the "PaperbackSourceTester" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackSourceTester")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "installSource" metadata.
        public enum installSource {
            /// Request type for "installSource".
            public typealias Input = SourceInstallRequest
            /// Response type for "installSource".
            public typealias Output = SourceInstallResponse
            /// Descriptor for "installSource".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackSourceTester"),
                method: "installSource"
            )
        }
        /// Namespace for "testSource" metadata.
        public enum testSource {
            /// Request type for "testSource".
            public typealias Input = SourceTestRequest
            /// Response type for "testSource".
            public typealias Output = SourceTestResponse
            /// Descriptor for "testSource".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackSourceTester"),
                method: "testSource"
            )
        }
        /// Descriptors for all methods in the "PaperbackSourceTester" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            installSource.descriptor,
            testSource.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "PaperbackSourceTester" service.
    public static let PaperbackSourceTester = GRPCCore.ServiceDescriptor(fullyQualifiedService: "PaperbackSourceTester")
}

// MARK: PaperbackSourceTester (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester {
    /// Streaming variant of the service protocol for the "PaperbackSourceTester" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "installSource" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SourceInstallRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SourceInstallResponse` messages.
        func installSource(
            request: GRPCCore.StreamingServerRequest<SourceInstallRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SourceInstallResponse>

        /// Handle the "testSource" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SourceTestRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SourceTestResponse` messages.
        func testSource(
            request: GRPCCore.StreamingServerRequest<SourceTestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SourceTestResponse>
    }

    /// Service protocol for the "PaperbackSourceTester" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: PaperbackSourceTester.StreamingServiceProtocol {
        /// Handle the "installSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceInstallRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SourceInstallResponse` message.
        func installSource(
            request: GRPCCore.ServerRequest<SourceInstallRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SourceInstallResponse>

        /// Handle the "testSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceTestRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SourceTestResponse` messages.
        func testSource(
            request: GRPCCore.ServerRequest<SourceTestRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SourceTestResponse>
    }

    /// Simple service protocol for the "PaperbackSourceTester" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: PaperbackSourceTester.ServiceProtocol {
        /// Handle the "installSource" method.
        ///
        /// - Parameters:
        ///   - request: A `SourceInstallRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SourceInstallResponse` to respond with.
        func installSource(
            request: SourceInstallRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SourceInstallResponse

        /// Handle the "testSource" method.
        ///
        /// - Parameters:
        ///   - request: A `SourceTestRequest` message.
        ///   - response: A response stream of `SourceTestResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func testSource(
            request: SourceTestRequest,
            response: GRPCCore.RPCWriter<SourceTestResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: PaperbackSourceTester.Method.installSource.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SourceInstallRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SourceInstallResponse>(),
            handler: { request, context in
                try await self.installSource(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: PaperbackSourceTester.Method.testSource.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SourceTestRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SourceTestResponse>(),
            handler: { request, context in
                try await self.testSource(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester.ServiceProtocol {
    public func installSource(
        request: GRPCCore.StreamingServerRequest<SourceInstallRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SourceInstallResponse> {
        let response = try await self.installSource(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func testSource(
        request: GRPCCore.StreamingServerRequest<SourceTestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SourceTestResponse> {
        let response = try await self.testSource(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester.SimpleServiceProtocol {
    public func installSource(
        request: GRPCCore.ServerRequest<SourceInstallRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SourceInstallResponse> {
        return GRPCCore.ServerResponse<SourceInstallResponse>(
            message: try await self.installSource(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func testSource(
        request: GRPCCore.ServerRequest<SourceTestRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SourceTestResponse> {
        return GRPCCore.StreamingServerResponse<SourceTestResponse>(
            metadata: [:],
            producer: { writer in
                try await self.testSource(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: PaperbackSourceTester (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester {
    /// Generated client protocol for the "PaperbackSourceTester" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "installSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceInstallRequest` message.
        ///   - serializer: A serializer for `SourceInstallRequest` messages.
        ///   - deserializer: A deserializer for `SourceInstallResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func installSource<Result>(
            request: GRPCCore.ClientRequest<SourceInstallRequest>,
            serializer: some GRPCCore.MessageSerializer<SourceInstallRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SourceInstallResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SourceInstallResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "testSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceTestRequest` message.
        ///   - serializer: A serializer for `SourceTestRequest` messages.
        ///   - deserializer: A deserializer for `SourceTestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func testSource<Result>(
            request: GRPCCore.ClientRequest<SourceTestRequest>,
            serializer: some GRPCCore.MessageSerializer<SourceTestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SourceTestResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SourceTestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "PaperbackSourceTester" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "installSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceInstallRequest` message.
        ///   - serializer: A serializer for `SourceInstallRequest` messages.
        ///   - deserializer: A deserializer for `SourceInstallResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func installSource<Result>(
            request: GRPCCore.ClientRequest<SourceInstallRequest>,
            serializer: some GRPCCore.MessageSerializer<SourceInstallRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SourceInstallResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SourceInstallResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: PaperbackSourceTester.Method.installSource.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "testSource" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SourceTestRequest` message.
        ///   - serializer: A serializer for `SourceTestRequest` messages.
        ///   - deserializer: A deserializer for `SourceTestResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func testSource<Result>(
            request: GRPCCore.ClientRequest<SourceTestRequest>,
            serializer: some GRPCCore.MessageSerializer<SourceTestRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SourceTestResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SourceTestResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: PaperbackSourceTester.Method.testSource.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester.ClientProtocol {
    /// Call the "installSource" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SourceInstallRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func installSource<Result>(
        request: GRPCCore.ClientRequest<SourceInstallRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SourceInstallResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.installSource(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SourceInstallRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SourceInstallResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "testSource" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SourceTestRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func testSource<Result>(
        request: GRPCCore.ClientRequest<SourceTestRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SourceTestResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.testSource(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SourceTestRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SourceTestResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PaperbackSourceTester.ClientProtocol {
    /// Call the "installSource" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func installSource<Result>(
        _ message: SourceInstallRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SourceInstallResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SourceInstallRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.installSource(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "testSource" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func testSource<Result>(
        _ message: SourceTestRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SourceTestResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SourceTestRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.testSource(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}